### ISSUE TITLE
Request for code source for BERT+Hard Prompt / soft prompt

### ISSUE THREAD

**Issue by OmkarModi** [wzh9969/HPT#6]
Hello,
I am carrying out few experiments on extreme multilabel classification. It would be really helpful if you could provide me a source code or detailed idea about HTC is carried out as flat classification task. 

Thankyou

**Comment by wzh9969** [comment]
These two baselines can be easily implemented with our codes. Modify how the template forms and the desired output labels in lines 111-138 of `train.py` as well as the loss function in line 210 of `models/prompt.py`. Then input `--graph ""` as an extra argument for training to remove the graph encoder. After removing everything about hierarchy in HTC, the problem is then flat classification. The idea of applying prompt methods to multi-label classification is similar to simple multi-class classification except we do a multi-label prediction at the `[MASK]` spot.

**Comment by OmkarModi** [comment]
Your prompt response and assistance were greatly appreciated, and I'm very thankful for your help!
